const SHEET_ID="1qy9zHFQgzfGZXiuDbw_kuMzmYiIHCGqY-hTnd3SnJ4A";
const CSV_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&gid=0`;
const API_URL="https://script.google.com/macros/s/AKfycbwKaguijjg5tQALRNkjAiaLzePHEWZRY-bEsFWpn-rSCHc4zW8kvVWJcBasZh0MXaQ/exec";
const columns=["Date","Actual Time","Invoice Time","Extra Time/Difference","Return Amount","Paid Amount","Paid Date","Balance"];
let records=[],filtered=[],adminPassword=sessionStorage.getItem("returnsAdminPassword")||"",expandedRow=null;
const $=s=>document.querySelector(s);

function parseCSV(text){const rows=[];let row=[],v="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++;}else if(c==='"')q=!q;else if(c===","&&!q){row.push(v);v="";}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;row.push(v);if(row.some(x=>x.trim()!==""))rows.push(row);row=[];v="";}else v+=c;}if(v!==""||row.length){row.push(v);if(row.some(x=>x.trim()!==""))rows.push(row);}return rows;}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function num(v){return Number(String(v??"").replace(/[$,]/g,""))||0;}
function money(v,plus=false){const n=num(v),f=new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Math.abs(n));return n<0?`-${f}`:plus&&n>0?`+${f}`:f;}
function duration(v){if(!v)return"—";const p=String(v).split(":");if(p.length<2)return String(v);const h=parseInt(p[0])||0,m=parseInt(p[1])||0;return h===0?`${m} min`:m===0?`${h} hrs`:`${h} hrs ${m} min`;}
function rowBalance(r){return r.Balance!==""?num(r.Balance):num(r["Paid Amount"])-num(r["Return Amount"]);}
function bclass(n){return n<0?"negative":n>0?"positive":"zero";}
function showMessage(t,type=""){const b=$("#messageBox");b.hidden=false;b.className=`message ${type}`;b.textContent=t;}
function hideMessage(){$("#messageBox").hidden=true;}
function setMode(){const a=!!adminPassword;$("#publicView").hidden=a;$("#adminView").hidden=!a;$("#loginBtn").hidden=a;$("#logoutBtn").hidden=!a;$("#modeText").textContent=a?"Admin mode: update paid amounts and save payments.":"Login to update and view full details.";}

function updateBalance(){const b=filtered.reduce((s,r)=>s+num(r["Paid Amount"]),0)-filtered.reduce((s,r)=>s+num(r["Return Amount"]),0);$("#overallBalance").textContent=money(b,true);$("#balanceCard").className=`balance-card ${bclass(b)}`;}
function renderPublic(){$("#publicBody").innerHTML=filtered.map(r=>`<tr><td><button class="date-btn" data-expand="${r.__rowNumber}">${esc(r.Date||"—")}</button></td><td class="money">${money(r["Return Amount"])}</td><td class="money">${r["Paid Amount"]!==""?money(r["Paid Amount"]):"—"}</td><td>${esc(r["Paid Date"]||"—")}</td></tr>${expandedRow===r.__rowNumber?`<tr class="expand-row"><td colspan="4"><div class="expand-grid"><div class="expand-item"><span>Actual Time</span><strong>${esc(duration(r["Actual Time"]))}</strong></div><div class="expand-item"><span>Invoice Time</span><strong>${esc(duration(r["Invoice Time"]))}</strong></div><div class="expand-item"><span>Extra Time/Difference</span><strong>${esc(duration(r["Extra Time/Difference"]))}</strong></div></div></td></tr>`:""}`).join("");
$("#publicBody").querySelectorAll("[data-expand]").forEach(b=>b.onclick=()=>{const n=Number(b.dataset.expand);expandedRow=expandedRow===n?null:n;renderPublic();});
$("#publicCards").innerHTML=filtered.map(r=>`<article class="record-card"><button class="record-summary" data-expand="${r.__rowNumber}"><div><strong>${esc(r.Date||"—")}</strong><span>Tap to expand</span></div><div><strong>${money(r["Return Amount"])}</strong><span>Return amount</span></div></button><div class="record-detail" ${expandedRow===r.__rowNumber?"":"hidden"}><div class="detail-row"><span>Paid Amount</span><span>${r["Paid Amount"]!==""?money(r["Paid Amount"]):"—"}</span></div><div class="detail-row"><span>Paid Date</span><span>${esc(r["Paid Date"]||"—")}</span></div><div class="detail-row"><span>Actual Time</span><span>${esc(duration(r["Actual Time"]))}</span></div><div class="detail-row"><span>Invoice Time</span><span>${esc(duration(r["Invoice Time"]))}</span></div><div class="detail-row"><span>Difference</span><span>${esc(duration(r["Extra Time/Difference"]))}</span></div></div></article>`).join("");
$("#publicCards").querySelectorAll("[data-expand]").forEach(b=>b.onclick=()=>{const n=Number(b.dataset.expand);expandedRow=expandedRow===n?null:n;renderPublic();});}

function renderAdmin(){$("#adminBody").innerHTML=filtered.map(r=>{const b=rowBalance(r);return `<tr><td>${esc(r.Date||"—")}</td><td>${esc(duration(r["Actual Time"]))}</td><td>${esc(duration(r["Invoice Time"]))}</td><td>${esc(duration(r["Extra Time/Difference"]))}</td><td class="money">${money(r["Return Amount"])}</td><td><input class="payment-input" type="number" min="0" step="0.01" value="${esc(r["Paid Amount"])}" data-input="${r.__rowNumber}"></td><td>${esc(r["Paid Date"]||"—")}</td><td><span class="balance-pill ${bclass(b)}">${money(b,true)}</span></td><td><button class="save-btn" data-save="${r.__rowNumber}">Save</button></td></tr>`;}).join("");
$("#adminBody").querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>savePayment(Number(b.dataset.save),b));
$("#adminCards").innerHTML=filtered.map(r=>{const b=rowBalance(r);return `<article class="record-card"><div class="record-summary"><div><strong>${esc(r.Date||"—")}</strong><span>Full details</span></div><span class="balance-pill ${bclass(b)}">${money(b,true)}</span></div><div class="record-detail"><div class="detail-row"><span>Actual Time</span><span>${esc(duration(r["Actual Time"]))}</span></div><div class="detail-row"><span>Invoice Time</span><span>${esc(duration(r["Invoice Time"]))}</span></div><div class="detail-row"><span>Difference</span><span>${esc(duration(r["Extra Time/Difference"]))}</span></div><div class="detail-row"><span>Return Amount</span><span>${money(r["Return Amount"])}</span></div><div class="detail-row"><span>Paid Date</span><span>${esc(r["Paid Date"]||"—")}</span></div><div class="mobile-pay"><input class="payment-input" type="number" min="0" step="0.01" value="${esc(r["Paid Amount"])}" data-input="${r.__rowNumber}"><button class="save-btn" data-save="${r.__rowNumber}">Save Payment</button></div></div></article>`;}).join("");
$("#adminCards").querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>savePayment(Number(b.dataset.save),b));}

function render(){renderPublic();renderAdmin();updateBalance();$("#recordCount").textContent=`Showing ${filtered.length} of ${records.length} record${records.length===1?"":"s"}`;}
function applySearch(){const q=$("#searchInput").value.toLowerCase();filtered=records.filter(r=>Object.values(r).join(" ").toLowerCase().includes(q));render();}
async function loadSheet(){try{hideMessage();$("#recordCount").textContent="Loading Google Sheet…";const res=await fetch(`${CSV_URL}&cache=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error("Could not load Google Sheet.");const rows=parseCSV(await res.text());const headers=rows[0].map(h=>h.trim());const missing=columns.filter(c=>!headers.includes(c));if(missing.length)throw new Error(`Missing heading(s): ${missing.join(", ")}`);records=rows.slice(1).map((cells,i)=>{const raw={};headers.forEach((h,j)=>raw[h]=(cells[j]??"").trim());const r=Object.fromEntries(columns.map(c=>[c,raw[c]??""]));r.__rowNumber=i+2;return r;}).filter(r=>r.Date!=="");filtered=[...records];render();}catch(e){showMessage(e.message,"error");$("#recordCount").textContent="Load failed";}}
async function apiRequest(p){const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(p),redirect:"follow"});return res.json();}
async function savePayment(row,button){const input=document.querySelector(`[data-input="${row}"]`),amount=Number(input.value);if(!Number.isFinite(amount)||amount<0){showMessage("Enter a valid paid amount.","error");return;}button.disabled=true;button.textContent="Saving…";try{const r=await apiRequest({action:"savePayment",rowNumber:row,paidAmount:amount,password:adminPassword});if(!r.success)throw new Error(r.error||"Payment could not be saved.");showMessage("Payment saved. Paid Date was added automatically.","success");await new Promise(x=>setTimeout(x,700));await loadSheet();}catch(e){showMessage(e.message,"error");}finally{button.disabled=false;button.textContent=button.closest(".mobile-pay")?"Save Payment":"Save";}}

$("#loginBtn").onclick=()=>$("#loginDialog").showModal();$("#closeLoginBtn").onclick=()=>$("#loginDialog").close();
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const p=$("#passwordInput").value.trim();if(!p)return;const b=e.submitter;b.disabled=true;b.textContent="Checking…";try{const r=await apiRequest({action:"login",password:p});if(!r.success)throw new Error(r.error||"Login failed.");adminPassword=p;sessionStorage.setItem("returnsAdminPassword",p);$("#passwordInput").value="";$("#loginDialog").close();setMode();render();showMessage("Admin login successful.","success");}catch(err){showMessage(err.message,"error");}finally{b.disabled=false;b.textContent="Login";}});
$("#logoutBtn").onclick=()=>{adminPassword="";sessionStorage.removeItem("returnsAdminPassword");setMode();render();};
$("#searchInput").addEventListener("input",applySearch);$("#refreshBtn").onclick=loadSheet;$("#themeBtn").onclick=e=>{document.body.classList.toggle("dark");e.currentTarget.textContent=document.body.classList.contains("dark")?"☀":"☾";};
setMode();loadSheet();