const SHEET_ID = "19_oqOHcci1Ba1LdQ1xozQCGElqGH6Yd3Kn6YMmF75qQ";
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&gid=0`;
const columns=["Date","Actual Time","Invoice Time","Extra Time/Difference","Amount","Invoice Paid Date","Return Date","Status"];
let records=[],filtered=[],sortKey="",sortDirection=1;
const $=s=>document.querySelector(s), head=$("#dataTable thead"), body=$("#dataTable tbody"), search=$("#searchInput"), filter=$("#statusFilter"), dialog=$("#detailsDialog"), details=$("#detailGrid"), errorBox=$("#errorBox");
function parseCSV(t){const rows=[];let row=[],v="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++;}else if(c==='"')q=!q;else if(c===","&&!q){row.push(v);v="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(v);if(row.some(x=>x.trim()!==""))rows.push(row);row=[];v="";}else v+=c;}if(v!==""||row.length){row.push(v);if(row.some(x=>x.trim()!==""))rows.push(row);}return rows;}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(v){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(String(v??"").replace(/[$,]/g,""))||0)}
function statusClass(v){const s=String(v||"").trim().toLowerCase();return ["pending","completed","returned","paid","approved"].includes(s)?s:"other"}
function renderHead(){head.innerHTML=`<tr>${columns.map(c=>`<th data-key="${esc(c)}">${esc(c)} ${sortKey===c?(sortDirection===1?"↑":"↓"):""}</th>`).join("")}</tr>`;head.querySelectorAll("th").forEach(th=>th.onclick=()=>sortBy(th.dataset.key));}
function render(){renderHead();body.innerHTML=filtered.length?filtered.map((r,i)=>`<tr data-i="${i}">${columns.map(c=>c==="Amount"?`<td class="amount">${money(r[c])}</td>`:c==="Status"?`<td><span class="status ${statusClass(r[c])}">${esc(r[c]||"Not set")}</span></td>`:`<td>${esc(r[c]||"—")}</td>`).join("")}</tr>`).join(""):`<tr><td class="empty" colspan="8">No matching records found.</td></tr>`;body.querySelectorAll("tr[data-i]").forEach(tr=>tr.onclick=()=>openDetails(filtered[Number(tr.dataset.i)]));$("#resultCount").textContent=`Showing ${filtered.length} of ${records.length} record${records.length===1?"":"s"}`;updateStats();}
function updateStats(){$("#totalRecords").textContent=filtered.length;$("#pendingRecords").textContent=filtered.filter(r=>r.Status.toLowerCase()==="pending").length;$("#completedRecords").textContent=filtered.filter(r=>["approved","completed","returned","paid"].includes(r.Status.toLowerCase())).length;$("#totalAmount").textContent=money(filtered.reduce((s,r)=>s+(Number(String(r.Amount).replace(/[$,]/g,""))||0),0));}
function apply(){const q=search.value.trim().toLowerCase(),s=filter.value.toLowerCase();filtered=records.filter(r=>Object.values(r).join(" ").toLowerCase().includes(q)&&(!s||r.Status.toLowerCase()===s));if(sortKey)sortData();render();}
function sortData(){filtered.sort((a,b)=>sortKey==="Amount"?((Number(String(a[sortKey]).replace(/[$,]/g,""))||0)-(Number(String(b[sortKey]).replace(/[$,]/g,""))||0))*sortDirection:String(a[sortKey]||"").localeCompare(String(b[sortKey]||""),undefined,{numeric:true})*sortDirection)}
function sortBy(k){if(sortKey===k)sortDirection*=-1;else{sortKey=k;sortDirection=1}sortData();render()}
function openDetails(r){details.innerHTML=columns.map(c=>`<div class="detail-item"><span>${esc(c)}</span><strong>${c==="Amount"?money(r[c]):esc(r[c]||"—")}</strong></div>`).join("");dialog.showModal()}
async function load(){try{errorBox.hidden=true;const res=await fetch(`${CSV_URL}&cache=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error(`Google returned ${res.status}`);const rows=parseCSV(await res.text());if(!rows.length)throw new Error("The Google Sheet is empty");const headers=rows[0].map(x=>x.trim());const missing=columns.filter(c=>!headers.includes(c));if(missing.length)throw new Error(`Missing heading(s): ${missing.join(", ")}`);records=rows.slice(1).map(cells=>{const raw={};headers.forEach((h,i)=>raw[h]=(cells[i]??"").trim());return Object.fromEntries(columns.map(c=>[c,raw[c]??""]))}).filter(r=>Object.values(r).some(v=>String(v).trim()!==""));filtered=[...records];filter.innerHTML='<option value="">All statuses</option>';[...new Set(records.map(r=>r.Status).filter(Boolean))].sort().forEach(s=>{const o=document.createElement("option");o.value=s;o.textContent=s;filter.appendChild(o)});render();}catch(e){console.error(e);renderHead();body.innerHTML='<tr><td class="empty" colspan="8">Google Sheet data could not be loaded.</td></tr>';$("#resultCount").textContent="Google Sheet could not be loaded";errorBox.hidden=false;errorBox.innerHTML=`<strong>Check your Google Sheet:</strong> Share it as “Anyone with the link – Viewer” and use the exact Row 1 headings listed in README.md.<br><small>${esc(e.message)}</small>`;updateStats();}}
search.oninput=apply;filter.onchange=apply;$("#clearBtn").onclick=()=>{search.value="";filter.value="";sortKey="";filtered=[...records];render()};$("#closeDialog").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};$("#themeToggle").onclick=e=>{document.body.classList.toggle("dark");e.currentTarget.textContent=document.body.classList.contains("dark")?"☀":"☾"};load();
